source 'https://rubygems.org'

gem 'celluloid', github: 'celluloid/celluloid', branch: 'master'
gem 'celluloid-io', github: 'celluloid/celluloid-io', branch: 'master'
gem 'reel', github: 'celluloid/reel', branch: 'master'
gem 'mongo'
gem 'fiber_connection_pool'

group :development do
  gem 'pry'
end
