source 'https://rubygems.org'

gem 'celluloid', github: 'celluloid/celluloid', branch: 'master'
gem 'celluloid-io', github: 'celluloid/celluloid-io', branch: 'master'
gem 'reel', github: 'celluloid/reel', branch: 'master'
gem 'ruby-mysql', github: 'rubencaro/ruby-mysql', branch: 'celluloid_io'
gem 'fiber_connection_pool'
